# Generated by Django 4.2 on 2023-05-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
